/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package donem.odevi.test;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.NoResultException;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bogdanovic44
 */
public class HastaDetayi extends javax.swing.JFrame {
    DefaultTableModel dtm=new DefaultTableModel();
    /**
     * Creates new form HastaDetayi
     */
    public HastaDetayi() {
        initComponents();
        String[] s={"Hasta Id","Hasta Adı","Hasta Soyadı","Yaşı","Randevu Kodu","Hastalıkları","İlaçları","Kullanıcı Adı","Şifre"};
        dtm.setColumnIdentifiers(s);
        hastaDetayi();
        jTable1.setModel(dtm);
    }
    
    void hastaDetayi(){
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("Omer_Kocbil_1321221009_BP2_ODEV2PU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("SELECT h FROM Hasta h WHERE h.hastaPK.hastaId=:hAdi");
        q.setParameter("hAdi", Hastahane.h1.hastaPK.getHastaId());
        Hasta h =(Hasta)q.getSingleResult();
        
        EntityManagerFactory emf2 = Persistence.createEntityManagerFactory("Omer_Kocbil_1321221009_BP2_ODEV2PU");
        EntityManager em2 = emf2.createEntityManager();
        Query q2 = em2.createQuery("SELECT h FROM Randevu h WHERE h.kullanici=:hAdi");
        q2.setParameter("hAdi", h.getHastaPK().getKullaniciAdi());
        Randevu r=null;
        try{
            r= (Randevu) q2.getSingleResult();
            Object[] o = {h.getHastaPK().getHastaId(),h.getAd(),h.getSoyad(),h.getYas(),r.getRandevuKodu(),h.getHastaliK1(),h.getIlac1(),h.getHastaPK().getKullaniciAdi(),h.getSifre()};
            dtm.addRow(o);
        } catch(NoResultException n){
            Object[] o = {h.getHastaPK().getHastaId(),h.getAd(),h.getSoyad(),h.getYas(),null,h.getHastaliK1(),h.getIlac1(),h.getHastaPK().getKullaniciAdi(),h.getSifre()};
            dtm.addRow(o);
        }
        if(h.getHastaliK1()!=null||h.getIlac2()!=null){
            Object[] o2={null,null,null,null,null,h.getHastaliK2(),h.getIlac2(),null,null};
            dtm.addRow(o2);
            if(h.getHastaliK3()!=null||h.getIlac3()!=null){
                Object[] o3={null,null,null,null,null,h.getHastaliK3(),h.getIlac3(),null,null};
                dtm.addRow(o3);
                if(h.getIlac4()!=null){
                    Object[] o4={null,null,null,null,null,null,h.getIlac4(),null,null};
                    dtm.addRow(o4);
                    if(h.getIlac5()!=null){
                        Object[] o5={null,null,null,null,null,null,h.getIlac5(),null,null};
                        dtm.addRow(o5);
                        if (h.getIlac6() != null) {
                            Object[] o6 = {null, null, null, null, null, null, h.getIlac6(),null,null};
                            dtm.addRow(o6);
                            if (h.getIlac7() != null) {
                                Object[] o7 = {null, null, null, null, null, null, h.getIlac7(),null,null};
                                dtm.addRow(o7);
                                if (h.getIlac8() != null) {
                                    Object[] o8 = {null, null, null, null, null, null, h.getIlac8(),null,null};
                                    dtm.addRow(o8);
                                    if (h.getIlac9() != null) {
                                        Object[] o9 = {null, null, null, null, null, null, h.getIlac9(),null,null};
                                        dtm.addRow(o9);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        this.setTitle(String.valueOf(h.getHastaPK().getHastaId())+" - "+h.getAd()+" "+h.getSoyad());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HastaDetayi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HastaDetayi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HastaDetayi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HastaDetayi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HastaDetayi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
